###Recupar todas las peliculas
GET http://localhost:1234/movies

### Recuperar una pelicula por id
GET http://localhost:1234/movies/a24d44ea-fe7a-11ee-94a9-c4651603e82d

### Recuperar todas las peliculas por un genero
GET http://localhost:1234/movies?genre=Crime

### Crear una peliculas
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "The Godfather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "rate": 0,
    "poster": "https://img.gruugo.com/product/4/49/14441494_max.jpg",
    "genre":[
        "Crime",
        "Drama"
    ]
}

###Actualizar una pnelicula
PATCH http://localhost:1234/movies/b5ca0034-fe74-11ee-8c02-c4651603e82d
Content-Type: application/json

{
    "title": "The Godfather 2",
    "year": 2000,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://img.gruugo.com/product/4/49/14441494_max.jpg",
    "rate": 3.4
}

###Eliminar una peliculas
DELETE http://localhost:1234/movies/a24d44ea-fe7a-11ee-94a9-c4651603e82d